package store

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Complete-archive export. The database-only snapshot (Export) lives in db.go,
// next to the connection it vacuums; this file adds the everything-else half.
//
// Why a second mode exists: witness's data root holds FOUR things it owns (see the
// Store doc comment) and only one of them is the database. `witness export <file>`
// snapshots that one, which the README presented as "back up the archive" — so an
// export was silently missing three pieces, two of which are NOT derivable from the
// database:
//
//   - config.toml — enabled lenses, runner binding, models. Restore without it and
//     distillation is silently OFF until the user reconfigures.
//   - lenses/ — the lens DEFINITIONS (lens.json + extract.md/review.md/emerge.md).
//     Prompt text appears NOWHERE in the database, so a lens the user AUTHORED is
//     simply gone. A bundled lens can be re-seeded from prompts/; a hand-written one
//     cannot, and for a non-person corpus it is the most valuable thing in the install.
//   - profile/ — the L4 narrative. Mostly derived from L2 facets and rebuilt by a
//     review, EXCEPT a hand-edited unified.md: editing that file directly is the
//     supported way to shape the cross-lens portrait (#100), and no other copy exists.
//
// exportInclude is an INCLUDE list, deliberately not an exclude list. A new entry
// added to the data root must be classified on purpose — here, or in exportSkip with
// a reason — rather than silently dropping out of every backup, which is precisely
// the bug this function exists to fix. TestExportAllClassifiesEveryRootEntry fails on
// an unclassified entry so the decision can't be skipped.
var exportInclude = []string{"config.toml", "lenses", "profile"}

// exportSkip records what is deliberately left OUT of a complete export, with the
// reason, so "is this missing on purpose?" is answerable from the source:
//
//	witness.db / -wal / -shm  the DB arrives via VACUUM INTO instead (WAL folded in);
//	                          copying the live files is the corruption mode export exists
//	                          to avoid.
//	witness.log               diagnostics, not archive data. Also the one file that grows
//	                          without bound, and it is regenerated by simply running.
//	runtime/                   OpenCode's PRIVATE runtime root (opencode.db, xdg/, the
//	                          serve pidfile). A disposable cache that reconcile() rebuilds
//	                          at Open, and large. Restoring it would restore a stale pid.
//
// Lock files (.worker.lock and friends) and RegisterLens's .tmp/.bak staging dirs are
// matched by shape rather than name — see classifyRootEntry.
var exportSkip = []string{"witness.db", "witness.db-wal", "witness.db-shm", "witness.log", "runtime"}

// renameForExport is os.Rename, overridable so a test can fail the final swap-into-place
// and prove the previous snapshot is put BACK rather than lost. A seam because that
// failure is otherwise unreachable: the rename is same-directory and immediately follows
// a successful write into that same directory, so nothing external can provoke it — and
// an untested recovery branch in a backup command is exactly the kind of code that turns
// out not to work on the one day it runs.
var renameForExport = os.Rename

// ExportItem is one top-level entry ExportAll wrote into the snapshot directory, so
// callers can report what was ACTUALLY captured rather than the fixed list they hoped
// for (a fresh archive may have no lenses or no profile yet).
type ExportItem struct {
	Name  string `json:"name"`  // path relative to the snapshot dir
	Dir   bool   `json:"dir"`   // true if Name is a directory
	Files int    `json:"files"` // regular files captured (1 for a plain file)
}

// ExportAll writes a COMPLETE archive snapshot into dstDir: the database (via the
// same consistent VACUUM INTO that Export uses) plus config.toml, lenses/ and
// profile/. Absent pieces are skipped, not errors — a fresh archive exports just a
// database.
//
// The snapshot directory has the SAME LAYOUT as the live data root, which is the
// whole trick: the result is itself a working archive, so restoring needs no import
// command and no undocumented reassembly. Either point witness at it in place
// (WITNESS_HOME=<dir>) or copy its contents over a stopped install's data dir.
// TestExportAllSnapshotIsARunnableDataDir pins that property.
//
// Safe against losing the PREVIOUS snapshot: everything is staged into a sibling
// .witness-tmp directory and swapped in only once complete (the RegisterLens
// pattern), with the old snapshot moved aside — not deleted — until the swap
// succeeds. A cron `export --all --force` that dies halfway therefore still leaves
// yesterday's backup intact, instead of replacing a good backup with a partial one.
//
// Like Export, it needs no worker stop: the database read is a consistent VACUUM
// INTO, and the three file pieces are written atomically by their owners
// (writeAtomic for config.toml, temp-dir+rename for lenses/).
func (s *Store) ExportAll(dstDir string, force bool) ([]ExportItem, error) {
	dstDir = strings.TrimSpace(dstDir)
	if dstDir == "" {
		return nil, fmt.Errorf("export: destination directory is required")
	}
	// Refuse to export onto the live data root. With --force the swap below would move
	// the user's real archive aside and then delete it, taking the WAL, the log and the
	// OpenCode runtime with it — while a worker might be mid-write. Compared by identity
	// (os.SameFile), so a symlink or a different spelling of the same directory is caught.
	if sameDir(dstDir, s.Root) {
		return nil, fmt.Errorf("export: %s IS the live data directory; export to a different path", dstDir)
	}
	existing := false
	if _, err := os.Stat(dstDir); err == nil {
		if !force {
			return nil, fmt.Errorf("export: %s already exists (use --force to overwrite)", dstDir)
		}
		existing = true
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("export: stat %s: %w", dstDir, err)
	}
	if parent := filepath.Dir(dstDir); parent != "" {
		if err := os.MkdirAll(parent, 0o700); err != nil {
			return nil, fmt.Errorf("export: mkdir %s: %w", parent, err)
		}
	}
	// Siblings of dstDir, so the swap is a same-filesystem rename (atomic).
	tmp, bak := dstDir+".witness-tmp", dstDir+".witness-bak"
	fail := func(err error) ([]ExportItem, error) {
		_ = os.RemoveAll(tmp)
		return nil, err
	}
	if err := os.RemoveAll(tmp); err != nil { // residue from an earlier crashed export
		return nil, fmt.Errorf("export: clear staging dir %s: %w", tmp, err)
	}
	if err := os.RemoveAll(bak); err != nil {
		return nil, fmt.Errorf("export: clear backup dir %s: %w", bak, err)
	}
	if err := os.MkdirAll(tmp, 0o700); err != nil { // 0700: private growth data
		return nil, fmt.Errorf("export: mkdir %s: %w", tmp, err)
	}
	// force=false: the staging dir is empty by construction, and VACUUM INTO requires a
	// fresh path. This also inherits Export's 0600 on the snapshot.
	if err := s.Export(filepath.Join(tmp, "witness.db"), false); err != nil {
		return fail(err)
	}
	items := []ExportItem{{Name: "witness.db", Files: 1}}
	for _, name := range exportInclude {
		src := filepath.Join(s.Root, name)
		fi, err := os.Stat(src)
		if os.IsNotExist(err) {
			continue // not every archive has one yet
		}
		if err != nil {
			return fail(fmt.Errorf("export: stat %s: %w", src, err))
		}
		dst := filepath.Join(tmp, name)
		if fi.IsDir() {
			n, err := copyTreeInto(src, dst)
			if err != nil {
				return fail(fmt.Errorf("export: copy %s: %w", name, err))
			}
			items = append(items, ExportItem{Name: name, Dir: true, Files: n})
			continue
		}
		if err := copyFileInto(src, dst); err != nil {
			return fail(fmt.Errorf("export: copy %s: %w", name, err))
		}
		items = append(items, ExportItem{Name: name, Files: 1})
	}
	// Swap: move any previous snapshot aside FIRST so a failed rename can put it back,
	// and only drop it once the new one is in place.
	if existing {
		if err := renameForExport(dstDir, bak); err != nil {
			return fail(fmt.Errorf("export: move existing %s aside: %w", dstDir, err))
		}
	}
	if err := renameForExport(tmp, dstDir); err != nil {
		restored := "was absent"
		if existing {
			if rerr := renameForExport(bak, dstDir); rerr == nil {
				restored = "restored"
			} else {
				restored = "left at " + bak
			}
		}
		return fail(fmt.Errorf("export: swap snapshot into %s (previous snapshot %s): %w", dstDir, restored, err))
	}
	_ = os.RemoveAll(bak)
	return items, nil
}

// sameDir reports whether two paths are the same directory on disk (identity, not
// string equality — so a symlink, a trailing slash, or a relative spelling of the
// live data root is still recognized). A path that does not exist is not the same as
// anything, which is the common case (exporting to a new directory).
func sameDir(a, b string) bool {
	fa, err := os.Stat(a)
	if err != nil {
		return false
	}
	fb, err := os.Stat(b)
	if err != nil {
		return false
	}
	return os.SameFile(fa, fb)
}

// copyTreeInto copies a directory tree, returning how many regular files it wrote.
// Only directories and regular files are copied: a symlink is SKIPPED rather than
// followed, so a link planted in the registry can't make a backup reach outside the
// archive (and can't produce an infinite walk). RegisterLens's .tmp/.bak staging dirs
// are skipped too — a crash can leave one behind and it is not a lens.
func copyTreeInto(src, dst string) (int, error) {
	entries, err := os.ReadDir(src)
	if err != nil {
		return 0, err
	}
	if err := os.MkdirAll(dst, 0o700); err != nil {
		return 0, err
	}
	files := 0
	for _, e := range entries {
		name := e.Name()
		if isLensStagingDir(name) {
			continue
		}
		from, to := filepath.Join(src, name), filepath.Join(dst, name)
		switch {
		case e.IsDir():
			n, err := copyTreeInto(from, to)
			if err != nil {
				return files, err
			}
			files += n
		case e.Type().IsRegular():
			if err := copyFileInto(from, to); err != nil {
				return files, err
			}
			files++
		}
	}
	return files, nil
}

// copyFileInto copies one regular file, creating its parent and keeping the archive's
// 0600. It streams rather than slurping: raw text and prompts are small, but nothing
// here needs the whole file resident.
func copyFileInto(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o700); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	// Surface the close error: on a full disk the copy can succeed while close reports
	// the real failure, and a backup must not claim success it didn't achieve.
	return out.Close()
}

// classifyRootEntry answers "does a complete export capture this data-root entry?" for
// one filename: exported, deliberately skipped, or unclassified. It exists for the
// census guard in the tests — an entry witness creates in its data root that is
// neither exported nor listed as skipped is a silent backup hole, the exact defect
// ExportAll was added to close.
func classifyRootEntry(name string) (exported, skipped bool) {
	for _, in := range exportInclude {
		if name == in {
			return true, false
		}
	}
	for _, sk := range exportSkip {
		if name == sk {
			return false, true
		}
	}
	// Matched by shape, not name: process locks (.worker.lock, .lens-registry.lock,
	// .config-write.lock, .opencode-sync.lock, ...) are transient advisory files, and
	// .tmp/.bak are crash residue from an atomic swap. Neither is archive data.
	if strings.HasSuffix(name, ".lock") || isLensStagingDir(name) {
		return false, true
	}
	return false, false
}
